---
title: "The Role of Race and Mental Illness Diagnosis on Stigmatization of Homeless Individuals"
shorttitle: "STIGMA, HOMELESSNESS, MENTAL ILLNESS, AND RACE"
author:
  - name: Karen Veronica Becerra
    corresponding: true
    orcid: 0009-0006-4967-0955
    email: kvbecerra@uchicago.edu
    affiliations:
      - id: uchicago
        name: "The University of Chicago"
        group: MAPSS Psychology
        department: Department of Psychology
        address: 5848 S. University Avenue
        city: Chicago
        region: IL
        country: USA
        postal-code: 60637
blank-lines-above-author-note: 2
author-note:
  status-changes: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
abstract: "Homelessness in the United States is a persistent problem that can have serious implications on the well-being of homeless individuals. The present study focused on the role of race and mental illness diagnosis on the stigmatization of homeless individuals, specifically looking at the outcomes of the Attribution Questionnaire. This questionnaire assessed the aspects of social distance, blame, dangerousness, concern, and willingness to help of 215 participants varying in ages across adulthood. The study was a self-paced online form that used six experimental vignettes. The results indicated that there were no significant interactions of race x diagnosis on stigmatization. Additionally, race had no significant main effects, suggesting it was not a significant factor for stigmatization of homeless individuals. However, there were some significant main effects of diagnosis. Findings might suggest that future work in reducing mental illness stigma and increasing education could help decrease stigmatization of the homeless population."
keywords: [Homelessness, Stigmatization, Race, Mental Illness, Diagnosis, Attribution Questionnaire]
impact-statement: ~
floatsintext: true
numbered-lines: false
bibliography: "Stigmatization.bib"
suppress-title-page: false
link-citations: true
mask: false
masked-citations: []
draft-date: false
lang: en
language:
  citation-last-author-separator: "and"
  citation-masked-author: "Masked Citation"
  citation-masked-date: "n.d."
  citation-masked-title: "Masked Title"
  email: "Email"
  title-block-author-note: "Author Note"
  title-block-correspondence-note: "Correspondence concerning this article should be addressed to"
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; [credit.niso.org](https://credit.niso.org)) as follows:"
  title-impact-statement: "Impact Statement"
  references-meta-analysis: "References marked with an asterisk indicate studies included in the meta-analysis."
format:
  apaquarto-docx: 
    toc: false
  apaquarto-html: 
    toc: true
  apaquarto-pdf:
    documentmode: man
    keep-tex: true
fontsize: 12pt
mainfont: "Times New Roman"
donotrepeattitle: true
execute: 
  freeze: auto
  working-directory: project
---

```{r}
#| label: setup
#| include: false
library(conflicted)
library(tidyverse)
library(flextable)
library(ftExtra)
library(knitr)
conflicts_prefer(dplyr::filter, .quiet = TRUE)
conflicts_prefer(flextable::separate_header, .quiet = TRUE)

```
Homelessness in the United States and the struggle to give individuals adequate housing is a persistent problem. Before the Covid -19 pandemic, the number of homeless individuals was on the rise with 568,000 individuals experiencing homelessness in 2019, an increase of 15,000 from the previous year[@frostHomelessnessWasRise2020]. With the current Covid-19 pandemic, we can only predict that those numbers have continued to increase. In the United States, 2.4% of homeless individuals die each year (Stasha, 2020). We know that the general population often tries to distance itself from the stigmatized population, more specifically the homeless population. Homeless individuals face greater stigma and social isolation and often are removed from public parks and other locations because the general public does not want them too close. The problems caused by stigmatization, such as social distancing, can affect the homeless population in terms of resources that they have available such as sanitation centers, employment, and social support. Often the homeless population lacks resources and is exposed to the elements which can increase their mortality, as well as the chance of being malnourished, having parasitic infestations, periodontal disease, degenerative joint diseases, venereal diseases, cirrhosis, and hepatitis-related to intravenous (IV) drug abuse. Public attitudes toward homeless individuals can influence policies and the services provided to this population. The attitudes displayed through the stigma of homeless individuals can have an impact on both physical and psychological health and willingness to access services. The impact of these stigmas has shown to have serious implications on the well-being of homeless individuals. The present study examined factors that could predict levels of stigmatization expressed towards homeless individuals. 

## Literature review 
>Research on the stigma of mental illness, homelessness, and race highlights its harmful effects on health and social integration. @corriganPublicStigmaMental2009 examined public stigma, focusing on stereotypes like causal attribution (blaming individuals for their condition) and dangerousness (perceiving them as threatening). Using vignette-based experiments, the study found that people with psychiatric disorders, especially those with drug addiction, faced greater stigma than those with physical disabilities. This work laid the foundation for understanding how mental illness, particularly schizophrenia and substance use disorders, contributes to the stigmatization of homeless individuals.
>
>While @corriganAttributionModelPublic2003 provided insight into the role of mental illness in stigma, it did not delve deeply into the specific effects on health outcomes. In contrast,@weiszStigmatizedIdentitiesPsychological2018 explored the broader implications of homelessness stigma, demonstrating that it contributes to physical distress, poor health, and social avoidance. Their study used a sample of 175 volunteers attending a one-day homeless event, controlling for race, age, mental illness, and the duration of homelessness. They found that participants who experienced or anticipated stigma due to homelessness reported higher psychological distress, worse physical health, and greater reluctance to use social services. Additionally, participants of color reported even higher levels of distress, poorer health, and increased avoidance of services. This research emphasized the intersectionality of homelessness and race in stigma experiences, offering valuable insights into the compounded effects of multiple stigmas on individuals' well-being.
>
>@markowitzRaceGenderHomelessness2021 further explored the relationship between homelessness and race, examining how race and gender intersect with stigma. They hypothesized that black homeless individuals would be perceived as more blameworthy and dangerous than their white counterparts, and that social distance (i.e., the degree of separation individuals feel toward homeless persons) would be greater for black and male homeless individuals. The study employed a 2 × 2 design, varying race (black vs. white) and gender (male vs. female), and found that black homeless individuals were indeed perceived as more dangerous, though no significant difference was found in the level of social distance between black and white individuals. These findings highlighted the role of race in the perception of dangerousness, though the effect on blameworthiness was not supported. The limitations of this study included a sample of college-aged students, who may have been more tolerant than the general population, potentially affecting the results. This limitation was addressed in the present study by including a broader, more diverse participant pool.
>
> [@gattisPerceivedRacialSexual2016]focused on racial discrimination and stigma in a sample of 89 black adolescents and young adults who had experienced homelessness. The study linked racial discrimination and stigma to higher levels of depression, drawing on the social and minority stress models, which suggest that marginalized groups experience more psychological distress due to a lack of societal support. Their findings reinforced the notion that stigma, particularly racial stigma, contributes to greater psychological distress in homeless individuals. Although the study was limited by its small sample size and lack of data on the duration of homelessness, it underscored the importance of race in shaping the stigmatization of homeless individuals.
>
>In conclusion, the literature demonstrates that stigmatization due to homelessness, mental illness, and race significantly impacts individuals' psychological and physical health, social integration, and access to resources. The current study seeks to extend this body of research by examining how mental illness and race interact to influence stigma levels, providing a more nuanced understanding of the factors contributing to the stigmatization of homeless individuals

## Current Study
>Building on the research by @corriganPublicStigmaMental2009, @markowitzRaceGenderHomelessness2021, and @weiszStigmatizedIdentitiesPsychological2018 the current study aimed to explore how race and mental illness diagnosis impact the stigmatization of homeless individuals. The research specifically focused on mental illness, distinguishing between individuals with schizophrenia and those with substance use disorders, and examined how these factors interact with race in shaping stigma. Previous studies suggest that public stigma varies across mental health conditions and that race plays a crucial role in determining the intensity of stigma. Based on these findings, the present study hypothesized that race would significantly influence social distance, perceived danger, blameworthiness, and emotional responses (concern and help) toward homeless individuals. Specifically, it was predicted that black homeless individuals would experience greater social distance, be perceived as more dangerous and more blameworthy, and receive less concern and help compared to their white counterparts. Additionally, it was anticipated that individuals with substance use disorders would face higher levels of social distance, dangerousness, and blame, while individuals with schizophrenia would receive more concern and help. Lastly, the study predicted that race and mental illness diagnosis would interact to influence all aspects of stigmatization.

### Hypotheses 
#### Effect of Race on Stigmatization
> 1. Black homeless individuals will experience greater social distance.
> 2. Black homeless individuals will be perceived as more dangerous.
> 3. Black homeless individuals will be perceived as more blameworthy.
> 4. Black homeless individuals will receive less concern and help compared to white homeless individuals.

#### Effect of Mental Illness Diagnosis on Stigmatization

> 1. Individuals with substance use disorders will face higher levels of social distance.
> 2. Individuals with substance use disorders will be perceived as more dangerous.
> 3. Individuals with substance use disorders will be perceived as more blameworthy.
> 4. Individuals with schizophrenia will receive more concern and help.
> 5. Interaction Between Race and Mental Illness Diagnosis

#### Race and mental illness diagnosis interaction
> 1. Race and mental Illness diagnosis will interact to influence all aspects of stigmatization, including social distance, perceived danger, blameworthiness, concern, and willingness to help.

# Method

General remarks on method. This paragraph is optional.

Not all papers require each of these sections. Edit them as needed. Consult the [Journal Article Reporting Standards](https://apastyle.apa.org/jars) for what is needed for your type of article.

## Participants

Who are they? How were they recruited? Report criteria for participant inclusion and exclusion. Perhaps some basic demographic stats are in order. A table is a great way to avoid repetition in statistical reporting.

## Measures

This section can also be titled **Materials** or **Apparatus**. Whatever tools, equipment, or measurement devices used in the study should be described.

### Measure A

Describe Measure A.

### Measure B

Describe Measure B.

#### Subscale B1

A paragraph after a 4th-level header will appear on the same line as the header.

#### Subscale B2

A paragraph after a 4th-level header will appear on the same line as the header.

##### Subscale B2a

A paragraph after a 5th-level header will appear on the same line as the header.

##### Subscale B2b

A paragraph after a 5th-level header will appear on the same line as the header.

## Procedure

What did participants do? How are the data going to be analyzed?

# Results

## Descriptive Statistics

Describe the basic characteristics of the primary variables. My ideal is to describe the variables well enough that someone conducting a meta-analysis can include the study without needing to ask for additional information.

<!-- Add Additional Sections as Needed -->

# Discussion

Describe results in non-statistical terms. <!-- Add sections as needed. -->

## Limitations and Future Directions

Every study has limitations. Based on this study, some additional steps might include...

## Conclusion

Describe the main point of the paper.

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::
