---
title: "Data cleaning_ Stigmatization of homeless individuals "
output: html_document
---

```{r}
write.csv(SPSS_File_for_Experimental_Study_Karen, "Experimental_Study_Karen.csv", row.names = FALSE) # changed the original data file from SPSS to CSV file to clean the data. I only had acess to the data via SPSS as this was the only programming that I did through my undergraduate experience. 

```

```{r}
# read in data to look at what need to be cleaned 
stigmatization_data <- read.csv("Experimental_Study_Karen.csv") # i left the label this ways so that the final clean data that i actually use in my analisis will have a better name. 
head(stigmatization_data)  # Shows the first 6 rows
str(stigmatization_data)   # Shows the structure of the data
colnames(stigmatization_data)  # Lists all column names
#Make a column with particpant ID, change race column be more spacific so that it is clear that that the race is not about the particpants but rather the race of the homeless individual in the vignettes of this study . 

```
